<!--<template>-->
<!--    <h1>-->
<!--        FILTER-->
<!--    </h1>-->
<!--&lt;!&ndash;    <router-view v-slot="{ Component, route }">&ndash;&gt;-->
<!--&lt;!&ndash;        <div :key="route.name">&ndash;&gt;-->
<!--&lt;!&ndash;            <Component :is="Component" />&ndash;&gt;-->
<!--&lt;!&ndash;        </div>&ndash;&gt;-->
<!--&lt;!&ndash;    </router-view>&ndash;&gt;-->
<!--    <v-form-designer></v-form-designer>-->
<!--</template>-->

<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
    <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
             size="default" @submit.prevent>
        <el-form-item label="input" prop="name">
            <el-input v-model="formData.name" type="text" clearable></el-input>
        </el-form-item>
        <el-form-item label="" label-width="0" prop="price" class="required">
            <el-slider v-model="formData.price" :step="10" range></el-slider>
        </el-form-item>
        <el-form-item label="number" prop="bedrooms">
            <el-input-number v-model="formData.bedrooms" class="full-width-input" controls-position="right"
                             :min="-100000000000" :max="100000000000" :precision="0" :step="1"></el-input-number>
        </el-form-item>
        <el-form-item label="number" prop="bathrooms">
            <el-input-number v-model="formData.bathrooms" class="full-width-input" controls-position="right"
                             :min="-100000000000" :max="100000000000" :precision="0" :step="1"></el-input-number>
        </el-form-item>
        <el-form-item label="number" prop="storeys">
            <el-input-number v-model="formData.storeys" class="full-width-input" controls-position="right"
                             :min="-100000000000" :max="100000000000" :precision="0" :step="1"></el-input-number>
        </el-form-item>
        <el-form-item label="number" prop="garages">
            <el-input-number v-model="formData.garages" class="full-width-input" controls-position="right"
                             :min="-100000000000" :max="100000000000" :precision="0" :step="1"></el-input-number>
        </el-form-item>
    </el-form>

</template>

<script>
import {
    defineComponent,
    toRefs,
    reactive,
    getCurrentInstance
}
    from 'vue'
export default defineComponent({
    components: {},
    props: {},
    setup() {
        const state = reactive({
            formData: {
                name: "",
                price: null,
                bedrooms: 0,
                bathrooms: 0,
                storeys: 0,
                garages: 0,
            },
            rules: {
                price: [{
                    required: true,
                    message: 'Input value should be not null.',
                }, {
                    pattern: /^([hH][tT]{2}[pP]:\/\/|[hH][tT]{2}[pP][sS]:\/\/)(([A-Za-z0-9-~]+)\.)+([A-Za-z0-9-~\/])+$/,
                    trigger: ['blur', 'change'],
                    message: ''
                }],
            },
        })
        const instance = getCurrentInstance()
        const submitForm = () => {
            instance.proxy.$refs['vForm'].validate(valid => {
                if (!valid) return
                //TODO: 提交表单
            })
        }
        const resetForm = () => {
            instance.proxy.$refs['vForm'].resetFields()
        }
        return {
            ...toRefs(state),
            submitForm,
            resetForm
        }
    }
})

</script>

<style lang="scss">
.el-input-number.full-width-input,
.el-cascader.full-width-input {
    width: 100% !important;
}

.el-form-item--medium {
    .el-radio {
        line-height: 36px !important;
    }

    .el-rate {
        margin-top: 8px;
    }
}

.el-form-item--small {
    .el-radio {
        line-height: 32px !important;
    }

    .el-rate {
        margin-top: 6px;
    }
}

.el-form-item--mini {
    .el-radio {
        line-height: 28px !important;
    }

    .el-rate {
        margin-top: 4px;
    }
}

.clear-fix:before,
.clear-fix:after {
    display: table;
    content: "";
}

.clear-fix:after {
    clear: both;
}

.float-right {
    float: right;
}

</style>

<style lang="scss" scoped>
div.table-container {
    table.table-layout {
        width: 100%;
        table-layout: fixed;
        border-collapse: collapse;

        td.table-cell {
            display: table-cell;
            height: 36px;
            border: 1px solid #e1e2e3;
        }
    }
}

div.tab-container {}

.label-left-align :deep(.el-form-item__label) {
    text-align: left;
}

.label-center-align :deep(.el-form-item__label) {
    text-align: center;
}

.label-right-align :deep(.el-form-item__label) {
    text-align: right;
}

.custom-label {}

.static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    :deep(.el-divider--horizontal) {
        margin: 0;
    }
}

</style>

